ICON_CHOICES = (

(	'fa-android', 'fa-android'), 
(	'fa-gamepad', 'fa-gamepad'), 
(	'fa-apple', 'fa-apple'), 
(	'fa-mobile', 'fa-mobile'), 
(	'fa-stack-overflow', 'fa-stack-overflow'), 
(	'fa-slack', 'fa-slack'), 
(	'fa-git', 'fa-git'), 
(	'fa-bitbucket', 'fa-bitbucket'), 
(	'fa-code-fork', 'fa-code-fork'), 
(	'fa-github', 'fa-github'), 
(	'fa-gitlab', 'fa-gitlab'), 
(	'fa-terminal', 'fa-terminal'), 
(	'fa-file-code-o', 'fa-file-code-o'), 
(	'fa-html5', 'fa-html5'), 
(	'fa-desktop', 'fa-desktop'), 
(	'fa-user', 'fa-user'), 
(	'fa-cloud', 'fa-cloud'), 
(	'fa-server', 'fa-server'), 
(	'fa-jsfiddle', 'fa-jsfiddle'), 
(	'fa-linux', 'fa-linux'),
(	'fa-trophy', 'fa-trophy'), 
(	'fa-graduation-cap', 'fa-graduation-cap'), 
(	'fa-line-chart', 'fa-line-chart'), 
(	'fa-bar-chart', 'fa-bar-chart'), 
(	'fa-pie-chart', 'fa-pie-chart'), 
(	'fa-diamond', 'fa-diamond'), 
(	'fa-coffee', 'fa-coffee'), 

)