# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('attended', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Class',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateTimeField(verbose_name='Class date')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('names', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('github', models.URLField()),
                ('phone_number', models.IntegerField()),
                ('bio', models.CharField(max_length=140)),
                ('main_strengths', models.CharField(max_length=75)),
                ('current_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Guardian')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stud_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentProfile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ClassSession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
    ]
