# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateTimeField(verbose_name='Class date')),
                ('attended', models.BooleanField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach'),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
    ]
