# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_for_profile',
        ),
    ]
