# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_studentprofile_student_for_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='note',
            field=models.CharField(default='', max_length=250),
        ),
    ]
