# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160525_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('attended', models.BooleanField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class')),
            ],
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='coach_id',
        ),
        migrations.RemoveField(
            model_name='classrecord',
            name='student_id',
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='ClassRecord',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ClassSession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
    ]
