# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_studentprofile_current_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_prof',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
