# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20160527_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github_link', models.URLField(unique=True)),
                ('github_name', models.CharField(max_length=40, unique=True)),
                ('phone_number', models.IntegerField()),
                ('bio', models.CharField(max_length=140)),
                ('main_stack', models.CharField(max_length=75)),
                ('school', models.CharField(max_length=60)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
    ]
