# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20160525_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='class_id',
            new_name='_class',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='coach_id',
            new_name='coach',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='class_id',
            new_name='_class',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='coach_id',
            new_name='coach',
        ),
    ]
