# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='font_awesome_icon',
            field=models.CharField(choices=[('fa-android', 'fa-android'), ('fa-apple', 'fa-apple'), ('fa-mobile', 'fa-mobile'), ('fa-stack-overflow', 'fa-stack-overflow'), ('fa-slack', 'fa-slack'), ('fa-git', 'fa-git'), ('fa-bitbucket', 'fa-bitbucket'), ('fa-code-fork', 'fa-code-fork'), ('fa-github', 'fa-github'), ('fa-gitlab', 'fa-gitlab'), ('fa-terminal', 'fa-terminal'), ('fa-file-code-o', 'fa-file-code-o'), ('fa-html5', 'fa-html5'), ('fa-desktop', 'fa-desktop'), ('fa-user', 'fa-user'), ('fa-cloud', 'fa-cloud'), ('fa-server', 'fa-server'), ('fa-jsfiddle', 'fa-jsfiddle'), ('fa-linux', 'fa-linux')], default='fa-tasks', max_length=20),
        ),
    ]
