# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20160527_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='github_link',
        ),
    ]
