# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0006_auto_20160615_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentguardian',
            name='user',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
