# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_studentprofile_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
