# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20160527_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='student',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
