# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_studentguardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.IntegerField(max_length=11)),
                ('github_user_name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=140)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
    ]
