# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_studprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studprofile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
