# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20160620_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Team')),
            ],
        ),
    ]
