# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_team_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='coach',
            new_name='assistant_coach',
        ),
        migrations.AddField(
            model_name='team',
            name='head_coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.Coach'),
        ),
    ]
