# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20160620_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPhrase',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_phrase', models.CharField(max_length=30)),
            ],
        ),
    ]
