# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
